# 2021 NFL Team Ratings

In [1]:
import pandas as pd
import numpy as np
import random
from functools import reduce
import os
os.getcwd()

'/Users/jakesingleton/Documents/projects/football/code'

We will implement the Massey and Colley methods.

### 0. Data

In [2]:
# Loads data from nfl_game_data.ipynb to a data frame
def load_data(year):
    return pd.read_csv("../data/" + str(year) + "_nfl_game_data.csv")

### 1. Massey

In [3]:
# Implement Massey method

# get_massey() takes a data frame df, runs the Massey algorithm, and returns the Massey Matrix M and the results
# REQUIRED: columns called "Home Team", "Away Team", "Home Score", "Away Score", and "Margin"
# (Margin is defined by Home Score - Away Score)
def get_massey(df):
    # Build M
    # Get games played for each team
    diag = df['Home Team'].value_counts().append(df["Away Team"].value_counts())
    diag = diag.groupby(diag.index).sum()
    M = pd.DataFrame(np.diag(diag), index = diag.index, columns = diag.index)
    for team in M.index:
        sub_df = df[(df["Home Team"] == team) | (df["Away Team"] == team)].reset_index()
        for i in range(sub_df.shape[0]):
            if sub_df.at[i, "Home Team"] == team:
                opp = sub_df.at[i, "Away Team"]
            else:
                opp = sub_df.at[i, "Home Team"]
            M.at[team, opp] = M.at[team, opp] - 1
    #print(M)
    # Build point differential vector p
    df["Away Diff"] = df["Away Score"] - df["Home Score"]
    diff_home = df.groupby("Home Team").agg({"Margin": "sum"})
    diff_away = df.groupby("Away Team").agg({"Away Diff": "sum"})
    merged = diff_home.merge(diff_away, left_index = True, right_index = True, how = "outer").fillna(0)
    merged["diff"] = merged["Margin"] + merged["Away Diff"]
    #print(merged)
    p = np.array(merged["diff"])
    #print(p)
    # Get M-bar and p-bar 
    Mbar = M.copy()
    pbar = p.copy()
    Mbar.iloc[Mbar.shape[0] - 1] = 1
    pbar[-1] = 0
    #print(Mbar, pbar)
    # Ratings vector r
    r = np.linalg.solve(Mbar, pbar)
    # Results data frame
    ratings = pd.DataFrame({"Team": Mbar.index, "Rating": r})
    # Now obtain offensive and defensive rating vectors through clever algebra
    # T is square diagonal matrix holding number of games played
    T = np.identity(Mbar.shape[0])
    np.fill_diagonal(T, np.diag(M))
    #print(T)
    # P is off-diagonal matrix holding number of games played between two teams
    P = np.array(M.copy())
    np.fill_diagonal(P, 0)
    P = P * -1
    #print(P)
    # Points For vector f
    f = (df.groupby("Home Team").agg({"Home Score": "sum"})["Home Score"]
         .append(df.groupby("Away Team").agg({"Away Score": "sum"})["Away Score"]))
    f = f.groupby(f.index).sum()
    #print(f)
    # Get defensive rating vector d
    d = np.linalg.solve(T + P, T@r - f)
    ratings["D Rating"] = d
    # Get offensive rating vector o
    o = r - d
    ratings["O Rating"] = o
    ratings = ratings[["Team", "Rating", "O Rating", "D Rating"]]
    ratings = ratings.sort_values(by = "Rating", ascending = False)
    ratings["Rank"] = ratings["Rating"].rank(ascending = False)
    # Return Massey Matrix M and ratings data frame 
    return M, ratings.reset_index(drop = True)

In [4]:
teams = ["Duke", "Miami", "UNC", "UVA", "VT"]
examp = pd.DataFrame(data = {"Home Team": ["Duke", "Duke", "Duke", "Duke", "Miami", "Miami", "Miami", "UNC", "UNC", "UVA"],
                             "Away Team": ["Miami", "UNC", "UVA", "VT", "UNC", "UVA", "VT", "UVA", "VT", "VT"],
                             "Home Score": [7, 21, 7, 0, 34, 25, 27, 7, 3, 14],
                             "Away Score": [52, 24, 38, 45, 16, 17, 7, 5, 30, 52]})
examp["Margin"] = examp["Home Score"] - examp["Away Score"]
examp

  Home Team Away Team  Home Score  Away Score  Margin
0      Duke     Miami           7          52     -45
1      Duke       UNC          21          24      -3
2      Duke       UVA           7          38     -31
3      Duke        VT           0          45     -45
4     Miami       UNC          34          16      18
5     Miami       UVA          25          17       8
6     Miami        VT          27           7      20
7       UNC       UVA           7           5       2
8       UNC        VT           3          30     -27
9       UVA        VT          14          52     -38

In [5]:
# Export examp 
examp.to_csv("../data/examp_data.csv", index = False)

In [6]:
M_examp, ratings_examp = get_massey(examp)
ratings_examp

    Team  Rating   O Rating   D Rating  Rank
0  Miami    18.2  21.975000  -3.775000   1.0
1     VT    18.0  20.708333  -2.708333   2.0
2    UVA    -3.4   7.841667 -11.241667   3.0
3    UNC    -8.0   1.375000  -9.375000   4.0
4   Duke   -24.8   1.975000 -26.775000   5.0

This is a nice example to verify with the book! Exactly right.

### 2. Colley

In [7]:
# Implement Colley method

# get_colley() takes a data frame of df and the Massey Matrix M, runs the Colley algorithm, and returns the Colley Matrix C and the results
# REQUIRED: data frame like one for get_massey() and the outputs from get_massey()
def get_colley(df, M):
    # We can use the identity on Who's #1? page 24 to easily get the Colley Matrix C
    C = 2 * np.identity(M.shape[0]) + M
    # Get Win/Loss data
    df["Winner"] = np.where(df["Margin"] > 0, df["Home Team"], df["Away Team"])
    df["Loser"] = np.where(df["Margin"] > 0, df["Away Team"], df["Home Team"])
    wins = df.groupby("Winner").count()["Loser"]
    losses = df.groupby("Loser").count()["Winner"]
    teams = sorted(set(df[["Winner", "Loser"]].values.flatten()))
    w_l_dict = {}
    for team in teams:
        if team not in losses.index:
            w_l_dict[team] = wins[team] - 0
        elif team not in wins.index:
            w_l_dict[team] = 0 - losses[team]
        else:
            w_l_dict[team] = wins[team] - losses[team]
    # Get vector b for Colley algorithm
    w_l_diff = np.fromiter(w_l_dict.values(), dtype = float)
    b = 1 + 0.5 * w_l_diff
    # Results data frame
    r = np.linalg.solve(C, b)
    ratings = pd.DataFrame({"Team": teams, "Rating": r}).sort_values(by = "Rating", ascending = False)
    ratings["Rank"] = ratings["Rating"].rank(ascending = False)
    # Return Colley Matrix C and ratings data frame 
    return C, ratings.reset_index(drop = True)

In [8]:
C_examp, examp_colley_ratings = get_colley(examp, M_examp)
examp_colley_ratings

    Team    Rating  Rank
0  Miami  0.785714   1.0
1     VT  0.642857   2.0
2    UNC  0.500000   3.0
3    UVA  0.357143   4.0
4   Duke  0.214286   5.0

Perfect! Matches the book

### Rank Aggregation: Simulated Game Data

For each set of rankings, we can generate ${32 \choose 2} = 496$ pairwise matchups. For our Massey rankings, we will compute point differentials for these hypothetical matchups using the Massey ratings themselves. This makes sense since this is the underlying assumption of the Massey algorithm. For our Colley rankings, we will compute point differentials by the difference in `Rank` position. Then we use a combiner method on this simulated game data to create one set of ratings.

**Note that the `Home Team`, `Away Team`, etc. columns in the simulated game data are meaningless. They are there so that our algorithm will run and will not affect results.**

Once we have our simulated game data we make a subjective choice. In particular, we must apply a combiner method, which is just the name for a rating system. For now, I will re-apply Massey. Why? Because in the NFL, due to a relatively level playing field, point differential should better reflect team strength than wins and losses themselves. For CFB, I will probably employ Colley at this step, since you often see teams like Alabama brutally blow out the poor Citadel.

In [9]:
from itertools import combinations

# get_sim_game_dat() is a helper function
# Inputs: a rating list, rating method of choice, and losing score and generates simulated game data
# Output: appropriate simulated game data to be used by a combiner method
def get_sim_game_dat(rating_lst, method, losing_score):
    # Get team combinations for simulated game data matchups
    team_combos = list(combinations(rating_lst["Team"], 2))
    team1 = [matchup[0] for matchup in team_combos]
    team2 = [matchup[1] for matchup in team_combos]
    lst_sim_game_dat = (pd.DataFrame(data = {"Home Team": team1, "Away Team": team2})
                        .merge(rating_lst, left_on = "Home Team", right_on = "Team")
                        .merge(rating_lst, left_on = "Away Team", right_on = "Team", suffixes = ("_Home", "_Away"))
                        .drop(columns = ["Team_Home", "Team_Away"]))
    if method == "Massey":
        lst_sim_game_dat["Home Score"] = (np.where(lst_sim_game_dat["Rating_Home"] > lst_sim_game_dat["Rating_Away"],
                                                     losing_score + 
                                                     np.floor(lst_sim_game_dat["Rating_Home"] - 
                                                              lst_sim_game_dat["Rating_Away"]),
                                                     losing_score))
        lst_sim_game_dat["Away Score"] = (np.where(lst_sim_game_dat["Rating_Away"] > lst_sim_game_dat["Rating_Home"],
                                                     losing_score + 
                                                     np.floor(lst_sim_game_dat["Rating_Away"] - 
                                                              lst_sim_game_dat["Rating_Home"]),
                                                     losing_score))
    elif method == "Colley":
        lst_sim_game_dat["Home Score"] = (np.where(lst_sim_game_dat["Rank_Home"] < lst_sim_game_dat["Rank_Away"],
                                                     losing_score + 
                                                     np.floor(lst_sim_game_dat["Rank_Away"] - 
                                                              lst_sim_game_dat["Rank_Home"]),
                                                     losing_score))
        lst_sim_game_dat["Away Score"] = (np.where(lst_sim_game_dat["Rank_Away"] < lst_sim_game_dat["Rank_Home"],
                                                     losing_score + 
                                                     np.floor(lst_sim_game_dat["Rank_Home"] - 
                                                              lst_sim_game_dat["Rank_Away"]),
                                                     losing_score))
    else:
        pass
    lst_sim_game_dat["Margin"] = lst_sim_game_dat["Home Score"] - lst_sim_game_dat["Away Score"]
    return lst_sim_game_dat

In [10]:
# aggregate_lists() aggregates rating/ranking lists into one combind superior list
# Inputs: df of standard game data, lsts of rating/ranking lists, combiner_method (rating algorithm of our choice)
# Output: one superior rating/ranking list
def aggregate_lists(df, lsts, combiner_method):
    # Average losing score for simulated game data
    losing_scores = np.where(df["Margin"] > 0, df["Away Score"], df["Home Score"])
    avg_losing_score = np.floor(np.mean(losing_scores))
    # Get simulated game data
    massey_sim_dat = get_sim_game_dat(lsts[0], "Massey", avg_losing_score)
    colley_sim_dat = get_sim_game_dat(lsts[1], "Colley", avg_losing_score)
    # Store each data frame of simulated game data
    sim_game_data = [massey_sim_dat, colley_sim_dat]
    # Concat simulated game data into one data frame of simulated game data
    sim_game_data = pd.concat(sim_game_data, axis = 0, sort = False)
    # Make look like standard data frame of just game information
    sim_game_data = sim_game_data.loc[:, ["Home Team", "Away Team", "Home Score", "Away Score", "Margin"]]
    # Run the given algorithm on the simulated game data. This is known as the "combiner method"
    if combiner_method == get_colley:  # If the combiner method is Colley we need Massey Matrix M
        Massey_matrix = get_massey(sim_game_data)[0]
        res = combiner_method(sim_game_data, Massey_matrix)
        mat = res[0]
        ratings = res[1]
        # Arrange ratings properly and add Rank column
        ratings = ratings.sort_values(by = "Rating", ascending = False)
        ratings["Rank"] = ratings["Rating"].rank(ascending = False)
        return mat, ratings.reset_index(drop = True)
    else:
        res = combiner_method(sim_game_data)
        if len(res) > 1:  # If true then this is the Massey Method and so we need the matrix
            mat = res[0]
            ratings = res[1]
            # Arrange ratings properly and add Rank column
            ratings = ratings.sort_values(by = "Rating", ascending = False)
            ratings["Rank"] = ratings["Rating"].rank(ascending = False)
            return mat, ratings.reset_index(drop = True)
        else:
            # Arrange ratings properly and add Rank column
            ratings = ratings.sort_values(by = "Rating", ascending = False)
            ratings["Rank"] = ratings["Rating"].rank(ascending = False)
            return ratings.reset_index(drop = True)

In our 2020 tests, we had a tie in the Colley ratings between Atlanta and Carolina! Oh noooooooooo! Let's try breaking it by doing the following:
1. Check for H2H matchup winner (if there's a winner, we break the tie and stop)
2. Use the original combiner method ratings to break the tie

In this case, if there is no H2H winner, then since the tie has arisen with Colley used as the combiner method, we will look at the original Colley ratings to break the tie.

In [11]:
# Breaks a tie by checking for H2H matchup results, and then, if there are none, selecting the top team of an original
# rating list, i.e. a "partial dictator" list
# Input: df with game info, rating list with a tie, and "dictator" rating list that will break the tie
# Output: rating list with no ties
def break_tie(df, rating_lst_tie, rating_lst_dictator):
    # Get tied teams
    tied_teams = rating_lst_tie.groupby("Rank").filter(lambda sf: sf["Team"].count() > 1)["Team"].tolist()
    team1 = tied_teams[0]
    team2 = tied_teams[1]
    # Get data frame of game info for tie teams
    h2h = df[((df["Home Team"] == team1) & (df["Away Team"] == team2)) 
              | ((df["Home Team"] == team2) & (df["Away Team"] == team1))]
    # Put # wins for each team into dict
    num_wins = dict(h2h.groupby("Winner").count()["Loser"])
    # Check for H2H winner
    if max(num_wins.values()) - min(num_wins.values()) > 0:  # True if there is a H2H winner
        h2h_winner = max(num_wins, key = num_wins.get)
        h2h_loser = min(num_wins, key = num_wins.get)
    else:  # Find H2H winner in the dictator rating list
        tied_frame = rating_lst_dictator[rating_lst_dictator["Team"].isin(tied_teams)]
        h2h_winner = (tied_frame.loc[tied_frame["Rank"] == np.min(tied_frame["Rank"]), "Team"]).values[0]
        h2h_loser = (tied_frame.loc[tied_frame["Rank"] == np.max(tied_frame["Rank"]), "Team"]).values[0]
    # Change ranks in the list with the tie
    rating_lst_tie["Rank"] = np.where(rating_lst_tie["Team"] == h2h_winner,
                                      np.floor(rating_lst_tie["Rank"]), 
                                      rating_lst_tie["Rank"])
    rating_lst_tie["Rank"] = np.where(rating_lst_tie["Team"] == h2h_loser,
                                      np.ceil(rating_lst_tie["Rank"]),
                                      rating_lst_tie["Rank"])
    # Re-rank list
    rating_lst_tie["Rank"] = rating_lst_tie["Rank"].rank(ascending = True)
    # Return final rating list
    return rating_lst_tie.sort_values(by = "Rank", ascending = True)

Great! The Panthers are ahead of the Falcons because they were ahead in `full_2020_colley_ratings`, the "dictator" rating list.

### 2021 Ratings

We need 3 weeks of data to find a unique solution to the Masey and Colley algorithms. Hence, we need some of 2020's data to help us at the beginning of the 2021 season.

**Preseason**: We will regress 2020's final ratings by one-third, inspired by the function $y = \frac{1}{1.5^{w + 1}}$, which equals two-thirds when the input is zero. Hence this gives the desired regression percentage.

**In Season Idea 1**: $\text{Week} \ w_i \ \text{2021 Rating} = \frac{1}{1.5^{w_i + 1}}*\text{2020 Rating} + (1 - (\frac{1}{1.5^{w_i + 1}}))*\text{2021 rating with} \ w_i \ \text{2020 games replaced}$, for $w_i \in [1, 8]$.

This is a weighted average where the weight on 2020 ratings decreases exponentially. Now, to be able to still find a unique solution for our ratings, for ever week played I will replace that week's 2020 games with the corresponding week's 2021 games. For instance, after Week 1, I will remove all 2020 Week 1 games and replace them with all 2021 Week 1 games. This ensures we still have enough data to find unique solutions while also serving as its own weighting system that gives weight 0 to old 2020 games and weight 1 to new 2021 games.

The post-Week 8 ratings will be the last that consider 2020 data, and so post-Week 9 we will rely on 2021 data only. Thus for half the season we get (quickly diminishing) help from 2020 data, and after Week 9, when we should have a good idea who is good and who is bad, we use 2021 data only.

Note the function $y_i = \frac{1}{1.5^{w_i + 1}}$ where $y_i$ is the weight for week i $w_i$ is nice because, for the preseason $w_0$, we effectively regress the 2020 ratings the mean by one-third, a convention used by other popular forecasters like [538](https://fivethirtyeight.com/methodology/how-our-nfl-predictions-work/).

**Idea 2**: Just use $\text{Week} \ w_i \ \text{2021 Rating} = \frac{1}{1.5^{w_i + 1}}*\text{2020 Rating} + (1 - (\frac{1}{1.5^{w_i + 1}}))*\text{2021 rating with} \ {w_i} \ \text{early games replaced}$, for $w_i \in [1, 8]$, ignoring the replacement idea.

These ideas are fully implemented below in `do_ratings()`.

In [12]:
# replace_weeks() takes past game data and replaces it with corresponding new game data
# Will be used post-Weeks 1-8
def replace_weeks(datold, datnew):
    to_replace_df = datold.copy()  # Don't want to modify old game data
    #print(datold[0:33])
    to_replace_df.loc[to_replace_df["Week"].isin(datnew["Week"])] = np.nan  # Sets games to replace with NaN
    #print(to_replace_df[0:33])
    # Check if we have more games to replace (since especially for 2020, some games were canceled by COVID)
    num_to_concat = datnew.shape[0] - (to_replace_df.shape[0] - to_replace_df.dropna().shape[0])
    while num_to_concat > 0: 
        print(num_to_concat)
        to_replace_df = to_replace_df.append(pd.Series(), ignore_index = True)
        num_to_concat -= 1
    # Drop NaN rows and concat new 2021 data
    replaced = pd.concat([to_replace_df.dropna(axis = 0), datnew])
    # Clean replaced and return it
    replaced["Week"] = replaced["Week"].astype('int')
    return replaced.sort_values(by = "Game #", ascending = True).reset_index(drop = True)

In [13]:
# Given a week w, an old rating and new rating, returns weighted rating according to theory above
def get_weighted_rating(w, oldrating, newrating):
    y = 1 / (1.5 ** (w + 1))  # The weight
    rating = y * oldrating + (1 - y) * newrating
    #print(y)
    return rating

### Rating Flow

In [14]:
# Takes two data frames: one of old data and one of new data, a week, a boolean replace for
# if we want to replace old data or not, and runs the Massey/Colling/Aggregating process
# Returns Massey-aggregated ratings
def do_ratings(datold, datnew, week, replace = True):
    # Check if preseason or in season
    if week == 0:  # True if in preseason
        # Get standard Massey and Colley ratings
        Mold, masseyold = get_massey(datold)
        Cold, colleyold = get_colley(datold, Mold)
        masseyold.to_csv("../data/nfl_2021/week" + str(week) + "/2020standard_massey_ratings.csv", index = False)
        colleyold.to_csv("../data/nfl_2021/week" + str(week) + "/2020standard_colley_ratings.csv", index = False)
    
        # Aggregate the above ratings with Massey as dictator
        massey_agg = aggregate_lists(datold, [masseyold, colleyold], get_massey)
        massey_agg_ratings = massey_agg[1]
    
        # Check for ties
        massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        print("Is there a tie in the Massey-combined list?", massey_tie)
        while massey_tie:
            # Call break_tie()
            massey_agg_ratings = break_tie(datold, massey_agg_ratings, masseyold)
            # Check again for a tie
            massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        massey_agg_ratings.to_csv("../data/nfl_2021/week" + str(week) + "/2020aggregated_massey_ratings.csv", index = False)
    
        # Weight the resulting list
        massey_agg_ratings["Weighted Rating"] = get_weighted_rating(w, massey_agg_ratings["Rating"], 0)
        massey_agg_ratings["Weighted O Rating"] = get_weighted_rating(w, massey_agg_ratings["O Rating"], 0)
        massey_agg_ratings["Weighted D Rating"] = get_weighted_rating(w, massey_agg_ratings["D Rating"], 0)
    
        # Rank ratings
        massey_agg_ratings["Rank"] = massey_agg_ratings["Weighted Rating"].rank(ascending = False)
        massey_agg_ratings = massey_agg_ratings.sort_values(by = "Rank", ascending = True).reset_index(drop = True)
    
    elif (week >= 1) and (week <= 8):  # True if in season and still need help from old data
        # Get standard Massey and Colley ratings for old data
        Mold, masseyold = get_massey(datold)
        Cold, colleyold = get_colley(datold, Mold)
        masseyold.to_csv("../data/nfl_2021/week" + str(week) + "/2020standard_massey_ratings.csv", index = False)
        colleyold.to_csv("../data/nfl_2021/week" + str(week) + "/2020standard_colley_ratings.csv", index = False)
    
        # Aggregate the above ratings with Massey as dictator
        massey_agg = aggregate_lists(datold, [masseyold, colleyold], get_massey)
        massey_agg_ratings = massey_agg[1]
    
        # Check for ties
        massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        print("Is there a tie in the Massey-combined list?", massey_tie)
        while massey_tie:
            # Call break_tie()
            massey_agg_ratings = break_tie(datold, massey_agg_ratings, masseyold)
            # Check again for a tie
            massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        massey_agg_ratings.to_csv("../data/nfl_2021/week" + str(w) + "/2020aggregated_massey_ratings.csv", index = False)
        
        # Combine old data with new data
        if replace:  # TRUE if we want to replace when we combine
            datold_combined = replace_weeks(datold, datnew)
        else:  # If we just want to combine
            datold_combined = pd.concat([datold, datnew], axis = 0)
    
        # Get Massey and Colley with combined data
        Mold_combined, masseyold_combined = get_massey(datold_combined)
        Cold_combined, colleyold_combined = get_colley(datold_combined, Mold_combined)
        masseyold_combined.to_csv("../data/nfl_2021/week" + str(week) + "/20and21combined_massey_ratings.csv", index = False)
        colleyold_combined.to_csv("../data/nfl_2021/week" + str(week) + "/20and21combined_colley_ratings.csv", index = False)
    
        # Aggregate the above ratings with Massey as dictator
        massey_agg_combined = aggregate_lists(datold_combined, [masseyold_combined, colleyold_combined], get_massey)
        massey_agg_combined_ratings = massey_agg_combined[1]
    
        # Check for ties
        massey_combined_tie = not len(massey_agg_combined_ratings["Rank"].unique()) == 32
        print("Is there a tie in the Massey-combined combined list?", massey_combined_tie)
        while massey_combined_tie:
            # Call break_tie()
            massey_agg_combined_ratings = break_tie(datold_combined, massey_agg_combined_ratings, masseyold_combined)
            # Check again for a tie
            massey_combined_tie = not len(massey_agg_combined_ratings["Rank"].unique()) == 32
        massey_agg_combined_ratings.to_csv("../data/nfl_2021/week" + str(week) + "/20and21aggregated_combined_massey_ratings.csv", index = False)
    
        # Merge old ratings with new, replaced ratings
        massey_agg_ratings = massey_agg_ratings.merge(massey_agg_combined_ratings, on = "Team", suffixes = ("_old", "_new"))
       
        # Regress old ratings to the mean by 1/3
        massey_agg_ratings["Rating_old"] = get_weighted_rating(0, massey_agg_ratings["Rating_old"], 0)
        massey_agg_ratings["O Rating_old"] = get_weighted_rating(0, massey_agg_ratings["O Rating_old"], 0)
        massey_agg_ratings["D Rating_old"] = get_weighted_rating(0, massey_agg_ratings["D Rating_old"], 0)
    
        # Get weighted ratings
        massey_agg_ratings["Weighted Rating"] = massey_agg_ratings.apply(lambda x: get_weighted_rating(w, 
                                                                                               x["Rating_old"], 
                                                                                               x["Rating_new"]), 
                                                                         axis = 1)
        massey_agg_ratings["Weighted O Rating"] = massey_agg_ratings.apply(lambda x: get_weighted_rating(w, 
                                                                                               x["O Rating_old"], 
                                                                                               x["O Rating_new"]), 
                                                                         axis = 1)
        massey_agg_ratings["Weighted D Rating"] = massey_agg_ratings.apply(lambda x: get_weighted_rating(w, 
                                                                                               x["D Rating_old"], 
                                                                                               x["D Rating_new"]), 
                                                                         axis = 1)
        # Rank ratings
        massey_agg_ratings["Rank"] = massey_agg_ratings["Weighted Rating"].rank(ascending = False)
        massey_agg_ratings = massey_agg_ratings.sort_values(by = "Rank", ascending = True).reset_index(drop = True)
    
    else:  # True if through 9 weeks or more
        # Get standard Massey and Colley ratings for new data
        Mnew, masseynew = get_massey(datnew)
        Cnew, colleynew = get_colley(datnew, Mnew)
        masseynew.to_csv("../data/nfl_2021/week" + str(week) + "/2021standard_massey_ratings.csv", index = False)
        colleynew.to_csv("../data/nfl_2021/week" + str(week) + "/2021standard_colley_ratings.csv", index = False)
    
        # Aggregate the above ratings with Massey as dictator
        massey_agg = aggregate_lists(datnew, [masseynew, colleynew], get_massey)
        massey_agg_ratings = massey_agg[1]
    
        # Check for ties
        massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        print("Is there a tie in the Massey-combined list?", massey_tie)
        while massey_tie:
            # Call break_tie()
            massey_agg_ratings = break_tie(datnew, massey_agg_ratings, masseynew)
            # Check again for a tie
            massey_tie = not len(massey_agg_ratings["Rank"].unique()) == 32
        massey_agg_ratings.to_csv("../data/nfl_2021/week" + str(week) + "/2021aggregated_massey_ratings.csv", index = False)

    # Write final ratings to csv
    massey_agg_ratings.to_csv("../data/nfl_2021/week" + str(week) + "/week" + str(week) + "final_massey_ratings.csv", index = False) 

    # Return ratings!
    return massey_agg_ratings

In [15]:
# Rate!

## CHANGE AS NECESSARY 

# The data
datold = load_data(2020)
datnew = load_data(2021)

# How many weeks into the season we are
w = 11  # Through week 11

# Whether to replace
replace = False
    
final_ratings = do_ratings(datold, datnew, w, replace)
final_ratings

Is there a tie in the Massey-combined list? False

                        Team     Rating   O Rating   D Rating  Rank
0          Arizona Cardinals  12.578125  19.114600  -6.536475   1.0
1             Dallas Cowboys  11.640625  18.162517  -6.521892   2.0
2       Tampa Bay Buccaneers   9.296875  15.990642  -6.693767   3.0
3           Tennessee Titans   8.343750  15.172413  -6.828663   4.0
4          Green Bay Packers   8.343750  15.272413  -6.928663   5.0
5         Kansas City Chiefs   7.750000  14.642204  -6.892204   6.0
6       New England Patriots   7.343750  14.472413  -7.128663   7.0
7           Los Angeles Rams   6.359375  13.471892  -7.112517   8.0
8              Buffalo Bills   5.109375  12.963558  -7.854183   9.0
9           Baltimore Ravens   4.750000  12.658871  -7.908871  10.0
10      Los Angeles Chargers   4.265625  12.125017  -7.859392  11.0
11         Minnesota Vikings   4.125000  11.846371  -7.721371  12.0
12        Indianapolis Colts   2.953125  11.218767  -8.265642  13.0
13        New Orleans Saints   2.343750  10.872413  -8.528663  14.0
14        Cincinnati Bengals   2.250000  10.742204  -8.492204  15.0
15          Cleveland Browns   1.828125  10.672933  -8.844808  16.0
16       San Francisco 49ers   1.468750  10.318246  -8.849496  17.0
17       Philadelphia Eagles   0.046875   9.715642  -9.668767  18.0
18       Pittsburgh Steelers  -2.265625   8.592725 -10.858350  19.0
19         Carolina Panthers  -2.546875   8.485433 -11.032308  20.0
20            Denver Broncos  -2.609375   8.420850 -11.030225  21.0
21         Las Vegas Raiders  -3.171875   8.422933 -11.594808  22.0
22          Seattle Seahawks  -3.718750   8.257829 -11.976579  23.0
23  Washington Football Team  -5.218750   7.607829 -12.826579  24.0
24           New York Giants  -6.937500   7.198454 -14.135954  25.0
25           Atlanta Falcons  -8.687500   7.040121 -15.727621  26.0
26             Chicago Bears  -8.812500   6.844288 -15.656788  27.0
27            Miami Dolphins  -9.125000   6.821371 -15.946371  28.0
28            Houston Texans -10.890625   6.613558 -17.504183  29.0
29      Jacksonville Jaguars -11.437500   6.598454 -18.035954  30.0
30             New York Jets -12.671875   6.589600 -19.261475  31.0
31             Detroit Lions -12.703125   6.557308 -19.260433  32.0

### How did our ratings do?

In [16]:
# Make WoW data frame
rating_lst = []

for w in range(0, w + 1):
    sub_new = datnew[datnew["Week"] == w]
    rating_w = do_ratings(datold, datnew, w, replace).loc[:, ["Team", "Weighted Rating", "Weighted O Rating",
                                                             "Weighted D Rating", "Rank"]]
    rating_w.columns = [col + " Week " + str(w) if col != "Team" else "Team" for col in rating_w.columns]
    rating_lst.append(rating_w)

Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined combined list? False
Is there a tie in the Massey-combined list? False

/Users/jakesingleton/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1418: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

Is there a tie in the Massey-combined list? False
Is there a tie in the Massey-combined list? False

In [17]:
# Join
wow_df = reduce(lambda x, y: pd.merge(x, y, on = 'Team', how = "inner"), rating_lst)
wow_df.head()

,Team,Weighted Rating Week 0,Weighted O Rating Week 0,Weighted D Rating Week 0,Rank Week 0,Weighted Rating Week 1,Weighted O Rating Week 1,Weighted D Rating Week 1,Rank Week 1,Weighted Rating Week 2,...,Weighted D Rating Week 9,Rank Week 9,Weighted Rating Week 10,Weighted O Rating Week 10,Weighted D Rating Week 10,Rank Week 10,Weighted Rating Week 11,Weighted O Rating Week 11,Weighted D Rating Week 11,Rank Week 11
0,Tampa Bay Buccaneers,8.010417,13.105746,-5.095329,1.0,9.506366,15.785919,-6.279553,1.0,9.905285,...,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0
1,Kansas City Chiefs,7.239583,12.364774,-5.125190,2.0,8.903356,15.206019,-6.302663,3.0,9.347029,...,NaN,6.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,6.0
2,Buffalo Bills,7.135417,12.246024,-5.110607,3.0,9.395255,15.653820,-6.258565,2.0,9.997878,...,NaN,9.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,9.0
3,New Orleans Saints,6.906250,12.053663,-5.147413,4.0,7.262153,13.737886,-6.475734,5.0,7.357060,...,NaN,14.0,NaN,NaN,NaN,14.0,NaN,NaN,NaN,14.0
4,Green Bay Packers,6.822917,11.945329,-5.122413,5.0,8.388310,14.678743,-6.290433,4.0,8.805748,...,NaN,5.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,5.0

Noice. TO-DO: Use WoW ratings to determine accuracy rate. Use `Weighted Rating Week __` column to see if Team A's > Team B. If so, we predict Team A to win.

In [18]:
latest_ratings = wow_df[['Team', 'Weighted Rating Week ' + str(w)]]
latest_ratings

                        Team  Weighted Rating Week 11
0       Tampa Bay Buccaneers                      NaN
1         Kansas City Chiefs                      NaN
2              Buffalo Bills                      NaN
3         New Orleans Saints                      NaN
4          Green Bay Packers                      NaN
5           Baltimore Ravens                      NaN
6           Seattle Seahawks                      NaN
7        Pittsburgh Steelers                      NaN
8           Los Angeles Rams                      NaN
9           Tennessee Titans                      NaN
10            Miami Dolphins                      NaN
11        Indianapolis Colts                      NaN
12          Cleveland Browns                      NaN
13         Arizona Cardinals                      NaN
14         Las Vegas Raiders                      NaN
15      New England Patriots                      NaN
16             Chicago Bears                      NaN
17       San Francisco 49ers                      NaN
18      Los Angeles Chargers                      NaN
19         Minnesota Vikings                      NaN
20  Washington Football Team                      NaN
21         Carolina Panthers                      NaN
22            Denver Broncos                      NaN
23           Atlanta Falcons                      NaN
24           New York Giants                      NaN
25            Dallas Cowboys                      NaN
26        Cincinnati Bengals                      NaN
27             Detroit Lions                      NaN
28            Houston Texans                      NaN
29       Philadelphia Eagles                      NaN
30             New York Jets                      NaN
31      Jacksonville Jaguars                      NaN

In [19]:
datnew.head()

,Week,Game #,Home Team,Away Team,ID_Home,ID_Away,Home Score,Away Score,Margin,Away Diff,Winner,Loser
0,1,1,Tampa Bay Buccaneers,Dallas Cowboys,29,8,31,29,2,-2,Tampa Bay Buccaneers,Dallas Cowboys
1,1,2,Buffalo Bills,Pittsburgh Steelers,3,24,16,23,-7,7,Pittsburgh Steelers,Buffalo Bills
2,1,3,Atlanta Falcons,Philadelphia Eagles,1,23,6,32,-26,26,Philadelphia Eagles,Atlanta Falcons
3,1,4,Washington Football Team,Los Angeles Chargers,31,26,16,20,-4,4,Los Angeles Chargers,Washington Football Team
4,1,5,Tennessee Titans,Arizona Cardinals,30,0,13,38,-25,25,Arizona Cardinals,Tennessee Titans

In [20]:
# Contains WoW winners
datnew

,Week,Game #,Home Team,Away Team,ID_Home,ID_Away,Home Score,Away Score,Margin,Away Diff,Winner,Loser
0,1,1,Tampa Bay Buccaneers,Dallas Cowboys,29,8,31,29,2,-2,Tampa Bay Buccaneers,Dallas Cowboys
1,1,2,Buffalo Bills,Pittsburgh Steelers,3,24,16,23,-7,7,Pittsburgh Steelers,Buffalo Bills
2,1,3,Atlanta Falcons,Philadelphia Eagles,1,23,6,32,-26,26,Philadelphia Eagles,Atlanta Falcons
3,1,4,Washington Football Team,Los Angeles Chargers,31,26,16,20,-4,4,Los Angeles Chargers,Washington Football Team
4,1,5,Tennessee Titans,Arizona Cardinals,30,0,13,38,-25,25,Arizona Cardinals,Tennessee Titans
...,...,...,...,...,...,...,...,...,...,...,...,...
160,11,161,Las Vegas Raiders,Cincinnati Bengals,22,6,13,32,-19,19,Cincinnati Bengals,Las Vegas Raiders
161,11,162,Seattle Seahawks,Arizona Cardinals,28,0,13,23,-10,10,Arizona Cardinals,Seattle Seahawks
162,11,163,Kansas City Chiefs,Dallas Cowboys,15,8,19,9,10,-10,Kansas City Chiefs,Dallas Cowboys
163,11,164,Los Angeles Chargers,Pittsburgh Steelers,26,24,41,37,4,-4,Los Angeles Chargers,Pittsburgh Steelers
164,11,165,Tampa Bay Buccaneers,New York Giants,29,20,30,10,20,-20,Tampa Bay Buccaneers,New York Giants

In [21]:
# Get actual winners
def actual_winners():

SyntaxError: unexpected EOF while parsing (<ipython-input-21-15c7736d60ce>, line 3)

In [ ]:
# Gets hindsight accuracy
def hindsight_acc():

In [ ]:
get_massey(datnew)[1]

In [ ]:
M = get_massey(datnew)[0]
get_colley(datnew, M)[1]